export const GET_DIGEST = "GET_DIGEST";
export const GET_DIGEST_SUCCESS = "GET_DIGEST_SUCCESS";
export const GET_DIGEST_FAILURE = "GET_DIGEST_FAILURE";


export const GET_DIGESTS = "GET_DIGESTS";
export const GET_DIGESTS_SUCCESS = "GET_DIGESTS_SUCCESS";
export const GET_DIGESTS_FAILURE = "GET_DIGESTS_FAILURE";
